name: Build container image
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Docker image
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - arch: amd64
            os: ubuntu-24.04
          - arch: arm64
            os: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/oleggator/discobot-rs:${{ github.sha }}-${{ matrix.arch }}

  manifest:
    name: Create image manifest
    needs:
      - build
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge into Multi-Arch Image
        run: |
          docker buildx imagetools create \
            -t ghcr.io/oleggator/discobot-rs:latest \
            -t ghcr.io/oleggator/discobot-rs:${{ github.sha }} \
              ghcr.io/oleggator/discobot-rs:${{ github.sha }}-amd64 \
              ghcr.io/oleggator/discobot-rs:${{ github.sha }}-arm64
